In [ ]:
import numpy as np
                              # what is bam?
                              # Working of bam.
# define two pairs of vectors
x1 = np.array([1, 1, 1, -1])
y1 = np.array([1, -1])
x2 = np.array([-1, -1, 1, 1])
y2 = np.array([-1, 1])

# compute weight matrix W
W = np.outer(y1, x1) + np.outer(y2, x2)  #The np.outer() function is a NumPy function that computes the outer product of two arrays. 
                                        # It takes two 1-dimensional arrays as input and returns a 2-dimensional array as output.
                                          '''arr1 = np.array([1, 2, 3])
                                          arr2 = np.array([4, 5, 6])
                                          [[ 4  5  6]
                                           [ 8 10 12]
                                           [12 15 18]]'''
# define BAM function
def bam(x):
    y = np.dot(W, x)
    y = np.where(y >= 0, 1, -1)
    return y

# test BAM with inputs
x_test = np.array([1, -1, -1, -1])
y_test = bam(x_test)

# print output
print("Input x: ", x_test)
print("Output y: ", y_test)