In [1]:
#import libraries
import numpy as np

# Define the perceptron class
class Perceptron:
    def __init__(self, input_size, lr=0.1): 
        self.W = np.zeros(input_size + 1)   #weight matrix is initially initialized to 0 -> [0,0,0,0,0,0,0,0,0,0,0]
        self.lr = lr                        #learning rate (alpha)

    def activation_fn(self, x):
        return 1 if x >= 0 else 0  #binary step activation function
    
    def predict(self, v):
        x = np.insert(v, 0, 1)
        z = self.W.T.dot(x)                # dot product of weight matrix and instance of input array and .T is used for transpose
        a = self.activation_fn(z)          
        return a


    def train(self, X, Y, epochs):         #epochs is the number iterations the neural network will go through during the learning phase
        for _ in range(epochs):            # _ is used when Basically it means you are not interested in how many times the loop is run till now just that it should run some specific number of times overall
            for i in range(Y.shape[0]):    
                x = X[i]
                y = self.predict(x)
                e = Y[i] - y
                self.W = self.W + self.lr * e * np.insert(x, 0, 1)  #perceptron training function


# Define the input data and labels
#training input array
X = np.array([
    [0,0,0,0,0,0,0,0,0,0], # 0
    [0,0,0,0,0,0,0,0,0,1], # 1
    [0,0,0,0,0,0,0,0,1,0], # 2
    [0,0,0,0,0,0,0,0,1,1], # 3
    [0,0,0,0,0,0,0,1,0,0], # 4
    [0,0,0,0,0,0,0,1,0,1], # 5
    [0,0,0,0,0,0,0,1,1,0], # 6
    [0,0,0,0,0,0,0,1,1,1], # 7
    [0,0,0,0,0,0,1,0,0,0], # 8
    [0,0,0,0,0,0,1,0,0,1], # 9
])

Y = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])  

# Create the perceptron and train it
perceptron = Perceptron(input_size=10) 
perceptron.train(X, Y, epochs=100) 

# Test the perceptron on some input data
# Testing array
test_X = np.array([
    [0,0,0,0,0,0,0,0,0,0], # 0
    [0,0,0,0,0,0,0,0,0,1], # 1
    [0,0,0,0,0,0,0,0,1,0], # 2
    [0,0,0,0,0,0,0,0,1,1], # 3
    [0,0,0,0,0,0,0,1,0,0], # 4
    [0,0,0,0,0,0,0,1,0,1], # 5
    [0,0,0,0,0,0,0,1,1,0], # 6
    [0,0,0,0,0,0,0,1,1,1], # 7
    [0,0,0,0,0,0,1,0,0,0], # 8
    [0,0,0,0,0,0,1,0,0,1], # 9
])

for i in range(test_X.shape[0]):
  x = test_X[i]
  y = perceptron.predict(x)
  print(f'{x} is {"even" if y == 0 else "odd"}')


[0 0 0 0 0 0 0 0 0 0] is even
[0 0 0 0 0 0 0 0 0 1] is odd
[0 0 0 0 0 0 0 0 1 0] is even
[0 0 0 0 0 0 0 0 1 1] is odd
[0 0 0 0 0 0 0 1 0 0] is even
[0 0 0 0 0 0 0 1 0 1] is odd
[0 0 0 0 0 0 0 1 1 0] is even
[0 0 0 0 0 0 0 1 1 1] is odd
[0 0 0 0 0 0 1 0 0 0] is even
[0 0 0 0 0 0 1 0 0 1] is odd
